apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../base/

patches:
  - path: ./enable-https.yaml
  - target:
      kind: TLSOption
      name: relay-exec-no-h2
    patch: |-
      apiVersion: traefik.io/v1alpha1
      kind: TLSOption
      metadata:
        name: relay-exec-no-h2
        namespace: traefik-system
  - target:
      kind: Middleware
      name: relay-auth-middleware
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: traefik-system
  - target:
      kind: ConfigMap
      name: frontend-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: frontend-config
      data:
        VITE_API_URL: "https://rootenv.sviridov.lu/api/"
        __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "rootenv.sviridov.lu"
  - target:
      kind: NetworkPolicy
      name: relay-authenticator
    patch: |-
      - op: add
        path: /spec/ingress/0/from/-
        value:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik-system
  - target:
      kind: ConfigMap
      name: relay-images
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: relay-images
      data:
        image: "ghcr.io/alex-sviridov/rootenv/relay-exec:latest"
  - target:
      kind: Deployment
      name: labenv-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_CLASS
          value: "traefik"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_ANNOTATIONS
          value: "traefik.ingress.kubernetes.io/router.entrypoints=websecure"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_EXEC_INGRESS_BASE_PATH
          value: "/relay/exec"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_CONTROLLER_NAMESPACE
          value: "traefik-system"

images:
  - name: frontend
    newName: ghcr.io/alex-sviridov/rootenv/frontend
    newTag: latest
  - name: backend
    newName: ghcr.io/alex-sviridov/rootenv/backend
    newTag: latest
  - name: attempt-controller
    newName: ghcr.io/alex-sviridov/rootenv/attempt-controller
    newTag: latest
  - name: relay-authenticator
    newName: ghcr.io/alex-sviridov/rootenv/relay-authenticator
    newTag: latest
  - name: labenv-operator
    newName: ghcr.io/alex-sviridov/rootenv/labenv-operator
    newTag: latest