apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay
  namespace: rootenv-lab-vlg699euchqeri
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: relay
  namespace: rootenv-lab-vlg699euchqeri
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: relay
  namespace: rootenv-lab-vlg699euchqeri
subjects:
  - kind: ServiceAccount
    name: relay
    namespace: rootenv-lab-vlg699euchqeri
roleRef:
  kind: Role
  name: relay
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: relay-primitive
  name: relay-primitive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-primitive
  strategy: {}
  template:
    metadata:
      labels:
        app: relay-primitive
    spec:
      serviceAccountName: relay
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: relay-primitive
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        image: relay-primitive:aae5a700ea3d1abb56cbe332d0734dd5feeb87505f172698f62965f6813dd550
        imagePullPolicy: Always
        env:
        - name: RELAY_NAMESPACE
          value: namespace
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: relay
spec:
  selector:
    app: relay-primitive
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay-debug
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - backend:
              service:
                name: relay
                port:
                  number: 8080
            path: /relay/vlg699euchqeri
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-relay
spec:
  podSelector:
    matchLabels:
      app: relay-primitive
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 8080