apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: rootenv
build:
  local:
    useBuildkit: true
  insecureRegistries:
    - rootenv-registry:5000
    - localhost:5111
  artifacts:
    - image: rootenv-registry:5000/rootenv-backend
      context: services/backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'pb_hooks/*.pb.js'
            dest: '/app/pb_hooks'
        hooks:
          after:
            - container:
                command: ["sh", "-c", "kill -HUP 1"]
    - image: rootenv-registry:5000/rootenv-relay-ssh
      context: services/relay
      docker:
        dockerfile: ./ssh/Dockerfile
      sync:
        manual:
          - src: '.'
            dest: '/app'
    - image: rootenv-registry:5000/rootenv-contmgr
      context: services/contmgr
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '.'
            dest: '/app'
    - image: rootenv-registry:5000/rootenv-ubuntu-sshd
      context: labs/images/ubuntu-sshd
      docker:
        dockerfile: Dockerfile
    - image: rootenv-registry:5000/rootenv-frontend
      context: services/frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**'
            dest: '/app'
          - src: 'public/**'
            dest: '/app'
          - src: 'index.html'
            dest: '/app'
manifests:
  rawYaml: 
  - deploy/k8s/*.yaml
