apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: rootenv
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: backend
      context: services/backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'pb_hooks/*.pb.js'
            dest: '/app/pb_hooks'
        hooks:
          after:
            - container:
                command: ["sh", "-c", "kill -HUP 1"]
    - image: frontend
      context: services/frontend
      docker:
        dockerfile: Dockerfile
    - image: labenv-operator
      context: services/labenv-operator
      docker:
        dockerfile: Dockerfile
    - image: attempt-controller
      context: services/attempt-controller
      docker:
        dockerfile: Dockerfile
    - image: relay-exec
      context: services/relay
      docker:
        dockerfile: exec/Dockerfile
    - image: relay-grader
      context: services/relay
      docker:
        dockerfile: grader/Dockerfile
    - image: relay-authenticator
      context: services/relay-authenticator
      docker:
        dockerfile: Dockerfile
    - image: ubuntu-sshd
      context: labs/images/ubuntu-sshd
      docker:
        dockerfile: Dockerfile
    - image: ubuntu-analytics
      context: labs/images/ubuntu-analytics
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl: {}
  kubeContext: k3d-rootenv
manifests:
  kustomize:
    paths:
    - deploy/overlays/dev
resourceSelector:
  allow:
    - groupKind: "ConfigMap"
      image: 
        - ".data.exec"
        - ".data.grader"
        - ".data.ubuntu-sshd"
        - ".data.ubuntu-analytics"

profiles:
  - name: sandbox
    build:
      local:
        push: true
    deploy:
      kubeContext: rootenv-sandbox
    manifests:
      kustomize:
        paths:
          - deploy/overlays/sandbox 