apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: rootenv
build:
  local:
    push: false
  artifacts:
    - image: rootenv-backend
      context: services/backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'pb_hooks/*.pb.js'
            dest: '/app/pb_hooks'
        hooks:
          after:
            - container:
                command: ["sh", "-c", "kill -HUP 1"]
    - image: rootenv-relay-ssh
      context: services/relay
      docker:
        dockerfile: ./ssh/Dockerfile
      sync:
        manual:
          - src: '.'
            dest: '/app'
    - image: rootenv-contmgr
      context: services/contmgr
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '.'
            dest: '/app'
    - image: rootenv-frontend
      context: services/frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**'
            dest: '/app'
          - src: 'public/**'
            dest: '/app'
          - src: 'index.html'
            dest: '/app'
deploy:
  kubectl: {}
  kubeContext: k3d-rootenv
manifests:
  rawYaml:
  - deploy/base/*.yaml
