---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pb-data-pvc
  namespace: rootenv-infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi