apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: relay-ssh
  name: relay-ssh
  namespace: rootenv-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-ssh
  strategy: {}
  template:
    metadata:
      labels:
        app: relay-ssh
    spec:
      containers:
      - name: relay-ssh
        image: rootenv-registry:5000/rootenv-relay-ssh
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: relay-config
        - secretRef:
            name: relay-secrets
        readinessProbe:
          httpGet:
            path: /healthz 
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
status: {}
