services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: ${VITE_API_URL}
    develop:
      watch:
        - action: sync
          path: ../frontend/src
          target: /app/src
        - action: sync+restart
          path: ../frontend/package.json
          target: /app/package.json
        - action: rebuild
          path: ../frontend/package-lock.json

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    develop:
      watch:
        - action: sync+restart
          path: ../backend/pb_hooks
          target: /app/pb_hooks
    volumes:
      - ../backend/pb_data:/app/pb_data
      - ../backend/pb_migrations:/app/pb_migrations
    environment:
      PB_ORIGINS: ${ALLOWED_ORIGINS}
    restart: unless-stopped

  relay:
    build:
      context: ../relay
      dockerfile: Dockerfile.dev
    volumes:
      - ./server.key:/app/id_rsa:ro
    environment:
      RELAY_BACKEND_URL: ${RELAY_BACKEND_URL}
      RELAY_BACKEND_USERNAME: ${RELAY_BACKEND_USERNAME}
      RELAY_BACKEND_PASSWORD: ${RELAY_BACKEND_PASSWORD}
      RELAY_ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      RELAY_PRIVATE_KEY_PATH: /app/id_rsa
      RELAY_IDLE_TIMEOUT: ${RELAY_IDLE_TIMEOUT:-30m}
      PORT: "8080"
      LOG_LEVEL: debug
    develop:
      watch:
        - action: sync
          path: ../relay
          target: /app
          ignore:
            - tmp

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    post_start:
      - command: "nginx -s reload"
        user: root
    develop:
      watch:
        - action: sync+restart
          path: ./nginx-dev.conf
          target: /etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      - relay