apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend
  - name: backend
  - name: labenv-operator
  - name: attempt-controller
  - name: relay-exec
  - name: relay-authenticator

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Deployment
      name: labenv-operator-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_CLASS
          value: "traefik"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_ANNOTATIONS
          value: "traefik.ingress.kubernetes.io/router.entrypoints=web"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RELAY_INGRESS_BASE_PATH
          value: "/relay/exec"
