apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: rootenv-frontend
  - name: rootenv-backend
  - name: labenv-operator
  - name: attempt-controller
  - name: relay-exec

patches:
  - target:
      kind: Deployment
      name: labenv-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: RELAY_IMAGE
            value: "relay-exec:7ef4936c2e4f74ac37edc13f084f6c2148602b6eb040728526aa122b4b0c8e8f"
          - name: RELAY_INGRESS_CLASS
            value: "traefik"
          - name: RELAY_INGRESS_ANNOTATIONS
            value: "traefik.ingress.kubernetes.io/router.entrypoints=web"
          - name: RELAY_INGRESS_BASE_PATH
            value: "/relay/exec"
