name: Bug found
description: Something is not working as expected
labels: ["type/bug"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - frontend
        - backend
        - contmgr
        - relay-ssh
        - infra\deploy
        - lab 
        - not-sure
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened and how it differs from your expectations.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the issue. Be as specific as possible.
      placeholder: |
        1. Lab selected ...
        2. Requested infrastructure ...
        3. Opened console tab ...
        4. ...
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Attach any relevant logs, configs, or other that might help in diagnosing the issue. Make sure to remove any sensitive information before attaching.
      placeholder: |
        - Screenshot of the error message
        - Logs from the terminal
        - Configuration files
      render: shell