apiVersion: v1
data:
  ATTEMPT_CONTROLLER_BACKEND_TLS_VERIFY: "false"
  ATTEMPT_CONTROLLER_BACKEND_URL: http://backend-svc.rootenv-infra.svc.cluster.local:8090
kind: ConfigMap
metadata:
  name: attempt-controller-config
  namespace: rootenv-infra

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attempt-controller
  name: attempt-controller
  namespace: rootenv-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attempt-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: attempt-controller
    spec:
      serviceAccountName: attempt-controller
      containers:
      - name: attempt-controller
        image: attempt-controller
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: attempt-controller-config
        - secretRef:
            name: attempt-controller-secrets
status: {}
