apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace-infra.yaml
  - 05-frontend-config.yaml
  - 10-backend-pvc.yaml
  - 20-backend-deploy.yaml
  - 22-frontend-deploy.yaml
  - 30-backend-svc.yaml
  - 32-frontend-svc.yaml
  - 40-backend-ingress.yaml
  - 49-frontend-ingress.yaml
  - ../../services/labenv-operator/config/default
  - 55-relay-exec-image.yaml
  - 50-attempt-controller-secrets.yaml
  - 51-attempt-controller-serviceaccount.yaml
  - 53-attempt-controller.yaml
  - 60-relay-middleware.yaml
  - 61-relay-authenticator.yaml
  - 62-relay-auth-middleware.yaml