---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - namespaces
  - pods
  - resourcequotas
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - lab.rootenv.io
  resources:
  - labenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.rootenv.io
  resources:
  - labenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - lab.rootenv.io
  resources:
  - labenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - watch
