apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../base/

patches:
  - target:
      kind: TLSOption
      name: relay-exec-no-h2
    patch: |-
      apiVersion: traefik.io/v1alpha1
      kind: TLSOption
      metadata:
        name: relay-exec-no-h2
        namespace: traefik-system
  - target:
      kind: ConfigMap
      name: frontend-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: frontend-config
      data:
        VITE_API_URL: "https://rootenv.sviridov.lu/api/"
        __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "rootenv.sviridov.lu"

images:
  - name: rootenv-frontend
    newName: ghcr.io/alex-sviridov/rootenv/frontend
    newTag: sha-28a70ec 
  - name: rootenv-backend
    newName: ghcr.io/alex-sviridov/rootenv/backend
    newTag: sha-2032b77 